micronaut:
  server:
    context-path: /my-service
  reactor:
    context-propagation: true

coherence:
  session:
    default:
      config: coherence-cache-config.xml
      scope: app-scope

jvm:
  system:
    property:
      coherence.console.color: "false"