apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coherence-app
spec:
  serviceName: coherence-headless-service
  replicas: 2
  selector:
    matchLabels:
      app: coherence-app
  template:
    metadata:
      labels:
        app: coherence-app
    spec:
      containers:
        - name: coherence
          image: ghcr.io/techcrumbs/coherence-hello-world:latest
          imagePullPolicy: Always
          ports:
            - name: coherence
              containerPort: 7574 # default Coherence port
            - name: rest
              containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Dcoherence.cluster=my-cluster -Dcoherence.wka=coherence-headless-service -Dcoherence.wka.port=7574"  
